drivers: drm/phytium: add backlight class device to driver kconfig dependencies
when set DRM_PHYTIUM as Y and BACKLIGHT_CLASS_DEVICE as M caused ld error below:
phytium_panel.c:395:(.text+0xaec): undefined reference to `backlight_device_register'

Signed-off-by: Huangjie <huangjie1663@phytium.com.cn>